backend:
  name: github
  repo: Ghaida-jaaisa/noor-personal-portfolio  # ضع هنا اسم حسابك على GitHub واسم المستودع
  branch: main

media_folder: "public/images"   # أي صورة يرفعها المصمم ستذهب هنا
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"  # مكان حفظ ملفات المشاريع
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }